apiVersion: v1
kind: Service
metadata:
  name: keycloak-development
  labels:
    app: keycloak-development
spec:
  ports:
    - name: plaintext
      port: 80
      targetPort: 8080
  selector:
    app: keycloak-development
  type: LoadBalancer