apiVersion: v1
kind: Service
metadata:
  name: keycloak-development-service
  labels:
    app: keycloak-development
spec:
  ports:
    - port: 53582
      targetPort: 8080
  selector:
    app: keycloak-development