spring:
  application.name: crypto-wallet
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST}:53582/auth/realms/WalletKeycloak/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST}:6432/crypto_wallet?&targetServerType=master&ssl=false
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

resource-server:
  keycloak:
    endpoint-templates:
      token-issue-url-template: http://${KEYCLOAK_HOST}:53582/auth/realms/%s/protocol/openid-connect/token
      users-management-url-template: http://${KEYCLOAK_HOST}:53582/auth/admin/realms/%s/users
    clients:
      admin:
        realm: master
        client_id: admin-cli
        username: ${KEYCLOAK_ADMIN_USERNAME}
        password: ${KEYCLOAK_ADMIN_PASSWORD}
      user:
        realm: WalletKeycloak
        client_id: login-app

web-security:
  config:
    ant-pattern: /crypto-wallet/api/auth/**
